name = "CmeSIM"
uuid = "ec636833-6e17-4bd0-9f7f-432596dfc144"
authors = ["Martin Kunz <martinkunz@email.cz> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
